from .create_services_table_migration import CreateServicesTableMigration
from .create_additional_services_table_migration import CreateAdditionalServicesTableMigration
from .create_service_additional_services_table_migration import CreateServiceAdditionalServicesTableMigration
from .create_service_details_table_migration import CreateServiceDetailsTableMigration
from .create_users_table_migration import CreateUserTableMigration
from .create_orders_table_migration import CreateOrdersTableMigration
from .create_order_client_info_table_migration import CreateOrderClientInfoTableMigration
from .create_order_additional_services_table_migration import CreateOrderAdditionalServiceTableMigration
from .create_service_additional_services_table_migration import CreateServiceAdditionalServicesTableMigration
from .create_reviews_table_migration import CreateReviewsTableMigration
from .create_order_premises_info_table_migration import CreateOrderPremisesInfoTableMigration
from .create_order_service_info_table_migration import CreateOrderServiceInfoMigration

